if(typeof console!=="undefined"){console.log=function(){};console.warn=function(){};console.error=function(){};}
// FLOW_style_master_v6_FINAL — 36 styles (prompt only, for gemini.js)
// 이 파일은 gemini.js에서 require/import 하지 않고, 내용만 복사해 사용합니다.
//
// ★ v1.5 (2레이어 스키마):
//   - prompt: 렌더링 + 환경/시대 레이어 (sceneDesc에 항상 적용)
//   - humanIdentity (optional): 성별·연령 조건부 의상/헤어/장신구 (인물 캐릭터 charProps에만 적용)
//   humanIdentity가 없는 스타일은 전부 prompt에 포함된 것으로 간주.

const IMAGE_STYLES_V6 = {
    '1': { name_ko: '동양 현대 실사', name_en: 'Asian Live Photo', type: 'universal', recommended_nationality: '', prompt: 'Hyper-realistic cinematic photograph. East Asian facial features. Natural lighting. High-quality DSLR photography. Shallow depth of field. Film grain texture.' },
    '2': { name_ko: '서양 현대 실사', name_en: 'Western Live Photo', type: 'universal', recommended_nationality: 'western', prompt: 'Hyper-realistic cinematic photograph. Caucasian facial features. Natural lighting. High-quality DSLR photography. Shallow depth of field. Film grain texture.' },
    '3': { name_ko: '동남아 현대 실사', name_en: 'Southeast Asian Live Photo', type: 'universal', recommended_nationality: 'southeast_asian', prompt: 'Hyper-realistic cinematic photograph. Southeast Asian facial features. Warm tan skin tone. Natural lighting. High-quality DSLR photography. Shallow depth of field. Film grain texture.' },
    '4': { name_ko: '흑인 현대 실사', name_en: 'Black Live Photo', type: 'universal', recommended_nationality: 'black', prompt: 'Hyper-realistic cinematic photograph. African American facial features. Rich deep skin tones. Natural lighting. High-quality DSLR photography. Shallow depth of field. Film grain texture.' },
    '5': { name_ko: '동양 로맨틱 2D', name_en: 'Asian Romantic 2D', type: 'universal', recommended_nationality: '', prompt: 'Romantic 2D webtoon illustration. East Asian facial features. Delicate line work, soft coloring, detailed brush textures. Warm cozy atmosphere. Emotionally expressive characters.' },
    '6': { name_ko: '서양 로맨틱 2D', name_en: 'Western Romantic 2D', type: 'universal', recommended_nationality: 'western', prompt: 'Romantic 2D illustration. Caucasian facial features. Delicate line work, soft coloring, detailed brush textures. Warm cozy atmosphere. Emotionally expressive characters.' },
    '7': { name_ko: '동양 3D 디즈니', name_en: 'Asian 3D Disney', type: 'universal', recommended_nationality: '', prompt: 'Charming 3D animated illustration, Disney/Pixar style. East Asian facial features with monolid eyes. Soft rounded character designs. Rich textures. Warm cinematic lighting. Expressive facial features.' },
    '8': { name_ko: '서양 3D 디즈니', name_en: 'Western 3D Disney', type: 'universal', recommended_nationality: 'western', prompt: 'Charming 3D animated illustration, Disney/Pixar style. Caucasian facial features. Soft rounded character designs. Rich textures. Warm cinematic lighting. Expressive facial features.' },
    '9': { name_ko: '한국 전통 2D', name_en: 'Korean Traditional 2D', type: 'fixed', recommended_nationality: 'korean', prompt: '2D Korean historical webtoon. Bright hopeful tone. Warm sunshine. Brighter color palette. Resilient optimistic atmosphere. Traditional Hanok architecture background.', humanIdentity: 'Period-appropriate Hanbok with vibrant silk colors. Traditional Gat horsehair hat over Sangtu topknot for male. Daenggi braided hair tied with red ribbon or Jjokmeori pinned bun for female. Norigae ornaments.' },
    '10': { name_ko: '한국 전통 3D', name_en: 'Korean Traditional 3D', type: 'fixed', recommended_nationality: 'korean', prompt: '3D animated illustration, Disney/Pixar style, Joseon Dynasty Korea. East Asian facial features with monolid eyes. Traditional Hanok setting.', humanIdentity: 'Traditional Gat hat over Sangtu topknot for male. Jjokmeori pinned bun hairstyle for female. Vibrant Hanbok with silk texture for nobility. Norigae ornament for female.' },
    '11': { name_ko: '한국 역사드라마 실사', name_en: 'Korean Historical Drama', type: 'fixed', recommended_nationality: 'korean', prompt: 'Hyper-realistic cinematic photograph. Korean historical drama aesthetic. Joseon Dynasty. Authentic period details.', humanIdentity: 'Traditional Sangtu topknot hairstyle under Gat hat for male. Jjokmeori neatly pinned bun adorned with gold Binyeo hairpin for female. Noble Hanbok with rich embroidery.' },
    '12': { name_ko: '일본 애니', name_en: 'Japanese Anime', type: 'fixed', recommended_nationality: 'japanese', prompt: 'Modern Japanese anime illustration. Clean precise line work. Vibrant cel-shading. Expressive large eyes. Dynamic composition. Contemporary manga aesthetic.' },
    '13': { name_ko: '일본 전통', name_en: 'Japanese Traditional', type: 'fixed', recommended_nationality: 'japanese', prompt: 'Traditional Japanese Ukiyo-e woodblock print style. Edo period aesthetic. Bold flat color areas. Decorative pattern details. Cherry blossom motifs.', humanIdentity: 'Elegant kimono with obi sash. Wooden geta sandals.' },
    '14': { name_ko: '중국 전통', name_en: 'Chinese Traditional', type: 'fixed', recommended_nationality: 'chinese', prompt: 'Traditional Chinese illustration. Qing Dynasty aesthetic. Soft ink wash background. Classical Chinese courtyard setting.', humanIdentity: 'Flowing silk Hanfu robes with intricate phoenix embroidery. Ornate hairpin accessories for female. Traditional Guanmao official hat for male.' },
    '15': { name_ko: '서부극', name_en: 'Western', type: 'fixed', recommended_nationality: 'western', prompt: 'Classic American Western illustration. Dusty frontier town setting. Warm sepia and amber tones. Horse in background. Gritty rugged atmosphere.', humanIdentity: 'Wide-brim cowboy hat. Leather vest with sheriff badge. Cowboy boots with spurs.' },
    '16': { name_ko: '동남아 전통', name_en: 'Southeast Asian Traditional', type: 'fixed', recommended_nationality: 'southeast_asian', prompt: 'Traditional Southeast Asian illustration. Thai cultural aesthetic. Warm tan skin tone. Intricate golden temple architecture. Rich tropical colors.', humanIdentity: 'Ornate golden crown headdress. Traditional ceremonial Chut Thai costume with gold embroidery.' },
    '17': { name_ko: '인도 전통', name_en: 'Indian Traditional', type: 'fixed', recommended_nationality: 'indian', prompt: 'Traditional Indian Mughal miniature painting style. Rich jewel-toned colors. Elaborate Mughal palace architecture.', humanIdentity: 'Ornate Sari with gold embroidery for female. Traditional Sherwani with turban for male. Bindi dot on forehead. Gold jewelry and bangles.' },
    '18': { name_ko: '남미 전통', name_en: 'Latin American Traditional', type: 'fixed', recommended_nationality: 'latin', prompt: 'Traditional Latin American illustration. Aztec or Mayan cultural motifs. Warm olive to brown skin tones. Ancient stone temple setting. Bold geometric Aztec patterns.', humanIdentity: 'Vibrant feathered headdress. Ceremonial jade jewelry.' },
    '19': { name_ko: '아랍 전통', name_en: 'Arabian Traditional', type: 'fixed', recommended_nationality: 'arab', prompt: 'Traditional Arabian illustration. Middle Eastern cultural aesthetic. Warm olive skin tone. Intricate Islamic geometric patterns. Desert palace architecture.', humanIdentity: 'Ornate turban with jewel pin for male. Neatly trimmed beard. Hijab with gold headband for female. Flowing Thobe and Bisht robe.' },
    '20': { name_ko: '동양 수채화', name_en: 'Asian Watercolor', type: 'universal', recommended_nationality: '', prompt: 'Soft watercolor illustration. East Asian facial features. Flowing translucent color washes. Gentle wet-on-wet blending. Delicate paper texture. Dreamy pastel atmosphere.' },
    '21': { name_ko: '서양 수채화', name_en: 'Western Watercolor', type: 'universal', recommended_nationality: 'western', prompt: 'Soft watercolor illustration. Caucasian facial features. Flowing translucent color washes. Gentle wet-on-wet blending. Delicate paper texture. Dreamy pastel atmosphere.' },
    '22': { name_ko: '채색 수묵화', name_en: 'Colored Ink Wash', type: 'universal', recommended_nationality: '', prompt: 'Colored ink wash painting. Traditional East Asian brush strokes. Vivid color washes over bold ink lines. Rice paper texture. Expressive spontaneous brushwork.' },
    '23': { name_ko: '동양 사이버펑크', name_en: 'Asian Cyberpunk', type: 'universal', recommended_nationality: '', prompt: 'Neon-lit cyberpunk illustration. East Asian facial features. Futuristic dystopian cityscape. Rain-soaked reflective streets. High contrast neon colors. Dark atmospheric shadows.' },
    '24': { name_ko: '서양 사이버펑크', name_en: 'Western Cyberpunk', type: 'universal', recommended_nationality: 'western', prompt: 'Neon-lit cyberpunk illustration. Caucasian facial features. Futuristic dystopian cityscape. Rain-soaked reflective streets. High contrast neon colors. Dark atmospheric shadows.' },
    '25': { name_ko: '동양 판타지', name_en: 'Asian Fantasy', type: 'universal', recommended_nationality: '', prompt: 'Epic fantasy illustration. East Asian facial features. Magical glowing atmosphere. Dramatic cinematic lighting. Highly detailed environment. Rich saturated colors. Heroic composition.' },
    '26': { name_ko: '서양 판타지', name_en: 'Western Fantasy', type: 'universal', recommended_nationality: 'western', prompt: 'Epic fantasy illustration. Caucasian facial features. Magical glowing atmosphere. Dramatic cinematic lighting. Highly detailed environment. Rich saturated colors. Heroic composition.' },
    '27': { name_ko: '스틱맨', name_en: 'Stick Man', type: 'neutral', recommended_nationality: '', prompt: 'Humorous 2D cartoon illustration. Single stick figure character with oversized large round white head (much bigger than body), small dot eyes, expressive eyebrows, chunky rounded short arms and legs. Korean YouTube educational stick figure style — clean white smooth rounded body.', humanIdentity: 'Male character wearing tiny red necktie.' },
    '28': { name_ko: '스틱우먼', name_en: 'Stick Woman', type: 'neutral', recommended_nationality: '', prompt: 'Humorous 2D cartoon illustration. Single stick figure character with oversized large round white head (much bigger than body), small sparkling dot eyes, rosy blush cheeks, chunky rounded short arms and legs. Korean YouTube educational stick figure style — clean white smooth rounded body.', humanIdentity: 'Female character with eyelashes and happy smile. Wearing a pink dress and pink ribbon headband.' },
    '29': { name_ko: '치비', name_en: 'Chibi', type: 'neutral', recommended_nationality: '', prompt: 'Super-deformed chibi illustration. 2-head-ratio proportions. Oversized round eyes. Tiny cute body. Pastel soft colors. Adorable exaggerated expressions.' },
    '30': { name_ko: '픽셀아트', name_en: 'Pixel Art', type: 'neutral', recommended_nationality: '', prompt: 'Retro pixel art. 8-bit DOS game aesthetic. Limited color palette. Hard pixel edges. Nostalgic video game sprite style. Scanline texture overlay.' },
    '31': { name_ko: '마인크래프트', name_en: 'Minecraft', type: 'neutral', recommended_nationality: '', prompt: 'Minecraft blocky voxel style. Cubic character design. Block-based world. Flat textured surfaces. Bright saturated colors. Iconic sandbox game aesthetic.' },
    '32': { name_ko: '러프 3D', name_en: 'Rough 3D', type: 'neutral', recommended_nationality: '', prompt: 'Bright saturated rough 3D render. Early PlayStation-era polygon style. Visible low-poly geometry. Simple flat textures. Stiff character poses. Retro game screenshot aesthetic.' },
    '33': { name_ko: '레트로 만화', name_en: 'Retro Cartoon', type: 'neutral', recommended_nationality: '', prompt: 'Vintage 1950s American cartoon illustration. Bold black outlines. Flat cel-shaded colors. Exaggerated rubberhose animation style. Retro halftone dot texture.' },
    '34': { name_ko: '호러', name_en: 'Horror', type: 'neutral', recommended_nationality: '', prompt: 'Dark horror illustration. Deeply unsettling atmosphere. High contrast shadows. Desaturated cold color palette with blood red accents. Eerie supernatural tension.' },
    '35': { name_ko: '해골', name_en: 'Skeleton', type: 'neutral', recommended_nationality: '', prompt: 'Hyper-realistic photograph. Natural outdoor urban street background. Cinematic lighting.', humanIdentity: 'A person with a real human skull face (detailed realistic white bone skull, bulging realistic eyeballs popping out of hollow eye sockets, visible grinning teeth) and skeletal bone hands, wearing completely normal modern everyday clothes — crisp white shirt, black pinstripe suit, neat necktie. Skeleton skull head and bony skeleton hands contrasting with perfectly normal office outfit.' },
    '36': { name_ko: '투시 인체', name_en: 'X-Ray Body', type: 'neutral', recommended_nationality: '', prompt: 'Hyper-realistic 3D medical illustration. Transparent human body cross-section view. Half realistic outer body surface, half see-through showing detailed internal organs, bones, muscles and tissue layers. Blue translucent skin revealing glowing internal anatomy underneath. Detailed heart, lungs, stomach, spine, ribcage all visible. Dark background with dramatic blue and red medical lighting. Scientific educational style.' }
};
